### ISSUE TITLE
Project Checklist

### ISSUE THREAD

**Issue by ablionit** [ablionit/StolenFromSusie#1]
- [ ] **Pre Development**
    - [ ] Understand Requirements & Details
    - [ ]  Finalize Team
    - [ ]  SolCRM Update
    - [ ]  Setup GitHub
    - [ ]  Project Report
    - [ ]  Get Server Access - Update CRM

- [ ] **During Development**
    - [ ]  Design Guideline Set
    - [ ]  Get Designer Involve
    - [ ]  Design Checking & Finalize
 
    - [ ]  HTML, Responsive
    - [ ]  Test HTML, Responsive
    - [ ]  Show Client for Approval
    - [ ]  Handover HTML to Developer
 
    - [ ]  Development
    - [ ]  Check Functionality
    - [ ]  Update Client with Work Progress
    - [ ]  Test Functionality, Responsive Locally
    - [ ]  Matching with Approved Design
    - [ ]  No # Links on the site
    - [ ]  Developed By Link
    - [ ]  Upload Confirmation
    - [ ]  Site Upload
    - [ ]  Proper Testing for all functionality
    - [ ]  Form Submission test on Live
    - [ ]  Wordpress Sites
    - [ ]  Security Plugins
    - [ ]  Cache Plugins
    - [ ]  SEO Plugins
    - [ ]  Basic SEO
    - [ ]  Speed Optimization

- [ ] **Post Development**
    - [ ]  Client Training
    - [ ]  Project End
    - [ ]  Client Feedback
    - [ ]  Backup Reminder
    - [ ]  Client Re-knock reminder
    - [ ]  Project Feedback
    - [ ]  Team Members Feedback
    - [ ]  Update solCRM
